use crate::{Result, svd};
use std::path::Path;

pub fn generate_async_rt_rs(_device: &svd::Device) -> Result<String> {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED BY svdkit::hal\n");
    out.push_str("#![allow(dead_code)]\n");
    out.push_str("#![allow(non_snake_case)]\n\n");

    out.push_str("use core::cell::UnsafeCell;\n");
    out.push_str("use core::future::Future;\n");
    out.push_str("use core::pin::Pin;\n");
    out.push_str("use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};\n");
    out.push_str("use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};\n\n");

    out.push_str("static READY_MASK: AtomicU32 = AtomicU32::new(0);\n");
    out.push_str("static TICKS_MS: AtomicU32 = AtomicU32::new(0);\n\n");

    out.push_str("pub fn now_ms() -> u32 {\n");
    out.push_str("    TICKS_MS.load(Ordering::Relaxed)\n");
    out.push_str("}\n\n");

    out.push_str("pub fn on_tick() {\n");
    out.push_str("    TICKS_MS.fetch_add(1, Ordering::Relaxed);\n");
    out.push_str("    READY_MASK.store(u32::MAX, Ordering::Release);\n");
    out.push_str("}\n\n");

    out.push_str("pub struct Delay {\n");
    out.push_str("    start_ms: u32,\n");
    out.push_str("    duration_ms: u32,\n");
    out.push_str("    started: bool,\n");
    out.push_str("}\n\n");

    out.push_str("impl Delay {\n");
    out.push_str("    pub const fn ms(ms: u32) -> Self {\n");
    out.push_str("        Self { start_ms: 0, duration_ms: ms, started: false }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("impl Future for Delay {\n");
    out.push_str("    type Output = ();\n\n");
    out.push_str("    fn poll(mut self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Self::Output> {\n");
    out.push_str("        let now = now_ms();\n");
    out.push_str("        if !self.started {\n");
    out.push_str("            self.start_ms = now;\n");
    out.push_str("            self.started = true;\n");
    out.push_str("        }\n\n");
    out.push_str("        if now.wrapping_sub(self.start_ms) >= self.duration_ms {\n");
    out.push_str("            Poll::Ready(())\n");
    out.push_str("        } else {\n");
    out.push_str("            Poll::Pending\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub struct Signal {\n");
    out.push_str("    signaled: AtomicBool,\n");
    out.push_str("    waker: UnsafeCell<Option<Waker>>,\n");
    out.push_str("}\n\n");

    out.push_str("unsafe impl Sync for Signal {}\n\n");

    out.push_str("impl Signal {\n");
    out.push_str("    pub const fn new() -> Self {\n");
    out.push_str("        Self { signaled: AtomicBool::new(false), waker: UnsafeCell::new(None) }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn signal(&self) {\n");
    out.push_str("        self.signaled.store(true, Ordering::Release);\n");
    out.push_str("        unsafe {\n");
    out.push_str("            crate::rt::disable_interrupts();\n");
    out.push_str("            let waker = (&*self.waker.get()).as_ref().cloned();\n");
    out.push_str("            crate::rt::enable_interrupts();\n");
    out.push_str("            if let Some(w) = waker {\n");
    out.push_str("                w.wake();\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn wait(&self) -> Wait<'_> {\n");
    out.push_str("        Wait { s: self, registered: false }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub struct Wait<'a> {\n");
    out.push_str("    s: &'a Signal,\n");
    out.push_str("    registered: bool,\n");
    out.push_str("}\n\n");

    out.push_str("impl Future for Wait<'_> {\n");
    out.push_str("    type Output = ();\n\n");
    out.push_str("    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {\n");
    out.push_str("        if self.s.signaled.swap(false, Ordering::AcqRel) {\n");
    out.push_str("            return Poll::Ready(());\n");
    out.push_str("        }\n\n");
    out.push_str("        if !self.registered {\n");
    out.push_str("            let w = cx.waker().clone();\n");
    out.push_str("            unsafe {\n");
    out.push_str("                crate::rt::disable_interrupts();\n");
    out.push_str("                *self.s.waker.get() = Some(w);\n");
    out.push_str("                crate::rt::enable_interrupts();\n");
    out.push_str("            }\n");
    out.push_str("            self.registered = true;\n");
    out.push_str("        }\n\n");
    out.push_str("        Poll::Pending\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub struct Task<'a> {\n");
    out.push_str("    index: u8,\n");
    out.push_str("    data: *mut (),\n");
    out.push_str("    poll_fn: unsafe fn(*mut (), &mut Context<'_>) -> Poll<()>,\n");
    out.push_str("    completed: bool,\n");
    out.push_str("    _life: core::marker::PhantomData<&'a mut ()>,\n");
    out.push_str("}\n\n");

    out.push_str("impl<'a> Task<'a> {\n");
    out.push_str("    pub fn new<F>(index: u8, fut: &'a mut F) -> Self\n");
    out.push_str("    where\n");
    out.push_str("        F: Future<Output = ()> + 'a,\n");
    out.push_str("    {\n");
    out.push_str("        Self {\n");
    out.push_str("            index,\n");
    out.push_str("            data: (fut as *mut F).cast::<()>(),\n");
    out.push_str("            poll_fn: poll_future::<F>,\n");
    out.push_str("            completed: false,\n");
    out.push_str("            _life: core::marker::PhantomData,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    fn bit(&self) -> u32 {\n");
    out.push_str("        1u32 << (self.index as u32)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("unsafe fn poll_future<F>(data: *mut (), cx: &mut Context<'_>) -> Poll<()>\n");
    out.push_str("where\n");
    out.push_str("    F: Future<Output = ()>,\n");
    out.push_str("{\n");
    out.push_str("    let fut = &mut *(data as *mut F);\n");
    out.push_str("    Pin::new_unchecked(fut).poll(cx)\n");
    out.push_str("}\n\n");

    out.push_str("pub fn wake_task_index(index: u8) {\n");
    out.push_str("    let bit = 1u32 << (index as u32);\n");
    out.push_str("    READY_MASK.fetch_or(bit, Ordering::AcqRel);\n");
    out.push_str("}\n\n");

    out.push_str("pub struct Executor;\n\n");

    out.push_str("impl Executor {\n");
    out.push_str("    pub const fn new() -> Self {\n");
    out.push_str("        Self\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn run<'a>(&self, tasks: &mut [&mut Task<'a>]) -> ! {\n");
    out.push_str("        for t in tasks.iter() {\n");
    out.push_str("            wake_task_index(t.index);\n");
    out.push_str("        }\n\n");

    out.push_str("        loop {\n");
    out.push_str("            let ready = READY_MASK.swap(0, Ordering::AcqRel);\n");
    out.push_str("            if ready == 0 {\n");
    out.push_str("                unsafe { crate::rt::wait_for_interrupt() };\n");
    out.push_str("                continue;\n");
    out.push_str("            }\n\n");

    out.push_str("            for task in tasks.iter_mut() {\n");
    out.push_str("                if task.completed {\n");
    out.push_str("                    continue;\n");
    out.push_str("                }\n");
    out.push_str("                if (ready & task.bit()) == 0 {\n");
    out.push_str("                    continue;\n");
    out.push_str("                }\n\n");

    out.push_str("                let waker = unsafe { task_waker(*task as *const Task<'a>) };\n");
    out.push_str("                let mut cx = Context::from_waker(&waker);\n");
    out.push_str("                let polled = unsafe { (task.poll_fn)(task.data, &mut cx) };\n");
    out.push_str("                if let Poll::Ready(()) = polled {\n");
    out.push_str("                    task.completed = true;\n");
    out.push_str("                }\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("unsafe fn task_waker<'a>(task: *const Task<'a>) -> Waker {\n");
    out.push_str("    Waker::from_raw(RawWaker::new(task.cast::<()>(), &TASK_WAKER_VTABLE))\n");
    out.push_str("}\n\n");

    out.push_str("unsafe fn waker_clone(data: *const ()) -> RawWaker {\n");
    out.push_str("    RawWaker::new(data, &TASK_WAKER_VTABLE)\n");
    out.push_str("}\n\n");

    out.push_str("unsafe fn waker_wake(data: *const ()) {\n");
    out.push_str("    waker_wake_by_ref(data);\n");
    out.push_str("}\n\n");

    out.push_str("unsafe fn waker_wake_by_ref(data: *const ()) {\n");
    out.push_str("    let t = &*(data as *const Task<'_>);\n");
    out.push_str("    wake_task_index(t.index);\n");
    out.push_str("}\n\n");

    out.push_str("unsafe fn waker_drop(_: *const ()) {}\n\n");

    out.push_str("static TASK_WAKER_VTABLE: RawWakerVTable =\n");
    out.push_str("    RawWakerVTable::new(waker_clone, waker_wake, waker_wake_by_ref, waker_drop);\n");

    Ok(out)
}

pub fn generate_async_rt_file(device: &svd::Device) -> Result<crate::hal::GeneratedFile> {
    let stem = crate::hal::sanitize_file_stem(&device.name);
    let file_name = format!("{stem}_async_rt.rs");
    let content = generate_async_rt_rs(device)?;
    Ok(crate::hal::GeneratedFile { file_name, content })
}

pub fn write_async_rt_file(device: &svd::Device, out_dir: &Path) -> Result<std::path::PathBuf> {
    let generated = generate_async_rt_file(device)?;
    std::fs::create_dir_all(out_dir)?;
    let out_path = out_dir.join(&generated.file_name);
    std::fs::write(&out_path, generated.content)?;
    Ok(out_path)
}
