//! HAL-ish helper code generation on top of the generated PAC.
//!
//! The intent is to keep it minimal and dependency-free, similar to the PAC generator.

use crate::{Result, svd};
use std::path::Path;

pub mod async_rt;
pub mod cdc_acm;
pub mod clock;
pub mod gpio;
pub mod power;
pub mod timer;
pub mod uart;
pub mod usb;

#[derive(Debug, Clone)]
pub struct GeneratedFile {
    pub file_name: String,
    pub content: String,
}

#[derive(Debug, Clone)]
pub struct GeneratedDir {
    pub path: String,
    pub files: Vec<GeneratedFile>,
}

pub fn generate_device_hal_file(device: &svd::Device) -> Result<GeneratedFile> {
    let stem = sanitize_file_stem(&device.name);
    let file_name = format!("{stem}_hal.rs");
    let content = generate_device_hal_rs(device)?;
    Ok(GeneratedFile { file_name, content })
}

pub fn write_device_hal_file(device: &svd::Device, out_dir: &Path) -> Result<std::path::PathBuf> {
    let generated = generate_device_hal_file(device)?;
    std::fs::create_dir_all(out_dir)?;
    let out_path = out_dir.join(&generated.file_name);
    std::fs::write(&out_path, generated.content)?;
    Ok(out_path)
}

pub fn generate_device_hal_dir(device: &svd::Device) -> Result<GeneratedDir> {
    let dir_name = format!("{}_hal", sanitize_file_stem(&device.name));
    let mut files = Vec::new();

    let mut mod_lines = Vec::new();
    mod_lines.push("#[allow(dead_code)]".to_string());
    mod_lines.push("#[allow(non_snake_case)]".to_string());
    mod_lines.push("#[allow(clippy::eq_op)]".to_string());
    mod_lines.push("#[allow(clippy::erasing_op)]".to_string());
    mod_lines.push("#[allow(clippy::identity_op)]".to_string());
    mod_lines.push("#[allow(unsafe_op_in_unsafe_fn)]".to_string());
    mod_lines.push("#[allow(unused_imports)]".to_string());
    mod_lines.push("".to_string());

    let stem = sanitize_file_stem(&device.name);
    let pac_mod = format!("{stem}_pac");
    mod_lines.push(format!("use crate::{pac_mod} as pac;"));

    let gpio_ports = gpio::collect_gpio_ports(device);
    if !gpio_ports.is_empty() {
        mod_lines.push("pub mod gpio;".to_string());
    }

    let timers = timer::collect_timers(device);
    if !timers.is_empty() {
        mod_lines.push("pub mod timer;".to_string());
    }

    let uarts = uart::collect_uarts(device);
    if !uarts.is_empty() {
        mod_lines.push("pub mod uart;".to_string());
    }

    let usb_devices = usb::collect_usb_devices(device);
    let has_usb = !usb_devices.is_empty();
    if has_usb {
        mod_lines.push("pub mod usb;".to_string());
        mod_lines.push("pub mod cdc_acm;".to_string());
    } else {
        mod_lines.push("pub mod cdc_acm;".to_string());
    }

    let clocks = clock::collect_clocks(device);
    if !clocks.is_empty() {
        mod_lines.push("pub mod clock;".to_string());
    }

    let power_devices = power::collect_power_devices(device);
    if !power_devices.is_empty() {
        mod_lines.push("pub mod power;".to_string());
    }

    mod_lines.push("".to_string());
    files.push(GeneratedFile {
        file_name: "mod.rs".to_string(),
        content: mod_lines.join("\n"),
    });

    if !gpio_ports.is_empty() {
        let mut content = String::new();
        content.push_str("#[allow(dead_code)]\n");
        content.push_str("#[allow(non_snake_case)]\n\n");
        content.push_str("use super::pac;\n\n");

        for port in gpio_ports {
            content.push_str(&port.render()?);
            content.push('\n');
        }

        files.push(GeneratedFile {
            file_name: "gpio/mod.rs".to_string(),
            content,
        });
    }

    if !timers.is_empty() {
        let mut content = String::new();
        content.push_str("// AUTO-GENERATED BY svdkit::hal::timer\n");
        content.push_str("#[allow(dead_code)]\n");
        content.push_str("#[allow(non_snake_case)]\n\n");
        content.push_str("use super::pac;\n\n");

        for t in &timers {
            content.push_str(&t.render()?);
            content.push('\n');
        }

        files.push(GeneratedFile {
            file_name: "timer/mod.rs".to_string(),
            content,
        });
    }

    if !timers.is_empty() {
        let mut content = String::new();
        content.push_str("#[allow(dead_code)]\n");
        content.push_str("#[allow(non_snake_case)]\n\n");
        content.push_str("use super::pac;\n\n");

        for u in uarts {
            content.push_str(&u.render()?);
            content.push('\n');
        }

        files.push(GeneratedFile {
            file_name: "uart/mod.rs".to_string(),
            content,
        });
    }

    if has_usb {
        let mut content = String::new();
        content.push_str("#[allow(dead_code)]\n");
        content.push_str("#[allow(non_snake_case)]\n\n");
        content.push_str("use super::pac;\n\n");

        for usb in &usb_devices {
            content.push_str(&usb.render()?);
            content.push('\n');
        }

        files.push(GeneratedFile {
            file_name: "usb/mod.rs".to_string(),
            content,
        });
    }

    {
        let cdc_content = cdc_acm::generate_cdc_acm_content(device)?;
        files.push(GeneratedFile {
            file_name: "cdc_acm/mod.rs".to_string(),
            content: cdc_content,
        });
    }

    if !clocks.is_empty() {
        let mut content = String::new();
        content.push_str("#[allow(dead_code)]\n");
        content.push_str("#[allow(non_snake_case)]\n\n");
        content.push_str("use super::pac;\n\n");

        for c in clocks {
            content.push_str(&c.render()?);
            content.push('\n');
        }

        files.push(GeneratedFile {
            file_name: "clock/mod.rs".to_string(),
            content,
        });
    }

    if !power_devices.is_empty() {
        let mut content = String::new();
        content.push_str("#[allow(dead_code)]\n");
        content.push_str("#[allow(non_snake_case)]\n\n");
        content.push_str("use super::pac;\n\n");

        for p in power_devices {
            content.push_str(&p.render()?);
            content.push('\n');
        }

        files.push(GeneratedFile {
            file_name: "power/mod.rs".to_string(),
            content,
        });
    }

    Ok(GeneratedDir {
        path: dir_name,
        files,
    })
}

pub fn write_device_hal_dir(device: &svd::Device, out_dir: &Path) -> Result<std::path::PathBuf> {
    let generated = generate_device_hal_dir(device)?;
    let dir_path = out_dir.join(&generated.path);
    std::fs::create_dir_all(&dir_path)?;
    for file in generated.files {
        let file_path = dir_path.join(&file.file_name);
        if let Some(parent) = file_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&file_path, file.content)?;
    }
    Ok(dir_path)
}

pub fn generate_device_hal_rs(device: &svd::Device) -> Result<String> {
    let stem = sanitize_file_stem(&device.name);
    let mut out = String::new();

    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[allow(non_snake_case)]\n");
    out.push_str("#[allow(clippy::eq_op)]\n");
    out.push_str("#[allow(clippy::erasing_op)]\n");
    out.push_str("#[allow(clippy::identity_op)]\n");
    out.push_str("#[allow(unsafe_op_in_unsafe_fn)]\n\n");

    let pac_mod = format!("{stem}_pac");
    out.push_str(&format!("use crate::{pac_mod} as pac;\n\n"));

    let gpio_ports = gpio::collect_gpio_ports(device);
    let has_gpio_ports = !gpio_ports.is_empty();
    if has_gpio_ports {
        out.push_str("pub mod gpio {\n");
        out.push_str("    use super::pac;\n\n");

        for port in gpio_ports {
            out.push_str(&port.render()?);
            out.push('\n');
        }

        out.push_str("}\n");
    }

    let timers = timer::collect_timers(device);
    let has_timers = !timers.is_empty();
    if has_timers {
        if has_gpio_ports {
            out.push('\n');
        }
        out.push_str("pub mod timer {\n");
        out.push_str("    use super::pac;\n\n");
        for t in &timers {
            out.push_str(&t.render()?);
            out.push('\n');
        }
        out.push_str("}\n");
    }

    let uarts = uart::collect_uarts(device);
    let has_uarts = !uarts.is_empty();
    if has_uarts {
        if has_gpio_ports || has_timers {
            out.push('\n');
        }
        out.push_str("pub mod uart {\n");
        out.push_str("    use super::pac;\n\n");
        for u in uarts {
            out.push_str(&u.render()?);
            out.push('\n');
        }
        out.push_str("}\n");
    }

    let usb_devices = usb::collect_usb_devices(device);
    let has_usb = !usb_devices.is_empty();
    if has_usb {
        if has_gpio_ports || has_timers || has_uarts {
            out.push('\n');
        }
        out.push_str("pub mod usb {\n");
        out.push_str("    use super::pac;\n\n");
        for usb in &usb_devices {
            out.push_str(&usb.render()?);
            out.push('\n');
        }
        out.push_str("}\n\n");
    }
    if !has_usb {
        out.push('\n');
    }
    out.push_str("pub mod cdc_acm;\n");

    let clocks = clock::collect_clocks(device);
    let has_clocks = !clocks.is_empty();
    if has_clocks {
        if has_gpio_ports || has_timers || has_uarts || has_usb {
            out.push('\n');
        }
        out.push_str("pub mod clock {\n");
        out.push_str("    use super::pac;\n\n");
        for c in clocks {
            out.push_str(&c.render()?);
            out.push('\n');
        }
        out.push_str("}\n");
    }

    let power_devices = power::collect_power_devices(device);
    if !power_devices.is_empty() {
        if has_gpio_ports || has_timers || has_uarts || has_usb || has_clocks {
            out.push('\n');
        }
        out.push_str("pub mod power {\n");
        out.push_str("    use super::pac;\n\n");
        for p in power_devices {
            out.push_str(&p.render()?);
            out.push('\n');
        }
        out.push_str("}\n");
    }

    Ok(out)
}

pub fn sanitize_file_stem(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "device".to_string()
    } else {
        out
    }
}
