//! HAL-ish helper code generation on top of the generated PAC.
//!
//! The intent is to keep it minimal and dependency-free, similar to the PAC generator.

use crate::{Result, svd};
use std::path::Path;

/// A single generated file (same shape as `pac::GeneratedFile`).
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    pub file_name: String,
    pub content: String,
}

/// Generate a single Rust file `{device}_hal.rs`.
pub fn generate_device_hal_file(device: &svd::Device) -> Result<GeneratedFile> {
    let stem = sanitize_file_stem(&device.name);
    let file_name = format!("{stem}_hal.rs");
    let content = generate_device_hal_rs(device)?;
    Ok(GeneratedFile { file_name, content })
}

/// Write the generated `{device}_hal.rs` file into a directory.
pub fn write_device_hal_file(device: &svd::Device, out_dir: &Path) -> Result<std::path::PathBuf> {
    let generated = generate_device_hal_file(device)?;
    std::fs::create_dir_all(out_dir)?;
    let out_path = out_dir.join(&generated.file_name);
    std::fs::write(&out_path, generated.content)?;
    Ok(out_path)
}

pub fn generate_device_hal_rs(device: &svd::Device) -> Result<String> {
    let stem = sanitize_file_stem(&device.name);
    let mut out = String::new();

    out.push_str("// AUTO-GENERATED BY svdkit::hal\n");
    out.push_str("#![allow(dead_code)]\n");
    out.push_str("#![allow(non_snake_case)]\n\n");

    // We assume the PAC device file is included as a Rust module with the same name as the file stem,
    // e.g. `mod nrf52840;` for `nrf52840.rs`.
    out.push_str(&format!("use crate::{stem} as pac;\n\n"));

    // Generate GPIO helpers (P0/P1 style) if the device contains such peripherals.
    let gpio_ports = collect_gpio_ports(device);
    if !gpio_ports.is_empty() {
        out.push_str("pub mod gpio {\n");
        out.push_str("    use super::pac;\n\n");

        for port in gpio_ports {
            out.push_str(&port.render()?);
            out.push('\n');
        }

        out.push_str("}\n");
    }

    Ok(out)
}

// --------------------------- GPIO HAL generation ---------------------------

#[derive(Debug, Clone)]
struct GpioPortInfo {
    periph_name: String,
    periph_mod: String,
    hal_mod: String,
    field_outset: String,
    field_outclr: String,
    field_pin_cnf: String,
    pin_cnf_reg_path: String, // for enum naming, if needed later
    pin_fields: Vec<svd::Field>,
}

impl GpioPortInfo {
    fn render(&self) -> Result<String> {
        // We expose a minimal builder that:
        // - configures PIN_CNF[n] by RMW using SVD bitfields + enumerated values
        // - provides set_high/set_low via OUTSET/OUTCLR
        //
        // It does NOT depend on PAC `field_enums` to avoid name coupling; it uses numeric values.
        let mut s = String::new();

        s.push_str(&format!("    pub mod {} {{\n", self.hal_mod));
        s.push_str("        use super::pac;\n\n");
        s.push_str(&format!(
            "        pub type Port = pac::{}::RegisterBlock;\n\n",
            self.periph_mod
        ));
        s.push_str("        use core::marker::PhantomData;\n\n");

        s.push_str("        pub struct InputMode;\n");
        s.push_str("        pub struct OutputMode;\n\n");

        s.push_str("        #[inline(always)]\n");
        s.push_str("        pub unsafe fn steal() -> &'static Port {\n");
        s.push_str(&format!("            &*pac::{}::PTR\n", self.periph_mod));
        s.push_str("        }\n\n");

        // Small per-field enums extracted from SVD (only for known field names).
        // If a field lacks usable enumeratedValues, we fall back to raw bits setters.
        let mut enums_src = String::new();
        let mut builder_methods = String::new();

        for fname in ["DIR", "INPUT", "PULL", "DRIVE", "SENSE"] {
            if let Some(f) = self
                .pin_fields
                .iter()
                .find(|f| f.name.eq_ignore_ascii_case(fname))
            {
                if let Some(e) = render_field_enum(fname, f) {
                    enums_src.push_str(&e);
                    enums_src.push('\n');
                    builder_methods.push_str(&render_builder_setter(
                        &self.field_pin_cnf,
                        fname,
                        f,
                        true,
                    ));
                } else {
                    builder_methods.push_str(&render_builder_setter(
                        &self.field_pin_cnf,
                        fname,
                        f,
                        false,
                    ));
                }
            }
        }

        if !enums_src.is_empty() {
            s.push_str(&indent_block(&enums_src, 8));
            s.push('\n');
        }

        // Pin + builder (typestate: InputMode/OutputMode).
        s.push_str("        pub struct Pin<'a, Mode> {\n");
        s.push_str("            port: &'a Port,\n");
        s.push_str("            index: u8,\n");
        s.push_str("            _mode: PhantomData<Mode>,\n");
        s.push_str("        }\n\n");

        s.push_str("        impl<'a, Mode> Pin<'a, Mode> {\n");
        s.push_str("            #[inline(always)]\n");
        s.push_str("            pub fn builder(port: &'a Port, index: u8) -> PinBuilder<'a, InputMode> {\n");
        s.push_str(&format!(
            "                let reg = &port.{}[index as usize];\n",
            self.field_pin_cnf
        ));
        s.push_str("                let cnf = reg.read();\n");
        s.push_str("                PinBuilder { port, index, cnf, _mode: PhantomData }\n");
        s.push_str("            }\n\n");
        s.push_str("        }\n\n");

        s.push_str("        impl<'a> Pin<'a, OutputMode> {\n");
        s.push_str("            #[inline(always)]\n");
        s.push_str("            pub fn set_high(&self) {\n");
        s.push_str(&format!(
            "                self.port.{}.write(1u32 << (self.index as u32));\n",
            self.field_outset
        ));
        s.push_str("            }\n\n");
        s.push_str("            #[inline(always)]\n");
        s.push_str("            pub fn set_low(&self) {\n");
        s.push_str(&format!(
            "                self.port.{}.write(1u32 << (self.index as u32));\n",
            self.field_outclr
        ));
        s.push_str("            }\n");
        s.push_str("        }\n\n");

        s.push_str("        pub struct PinBuilder<'a, Mode> {\n");
        s.push_str("            port: &'a Port,\n");
        s.push_str("            index: u8,\n");
        s.push_str("            cnf: u32,\n");
        s.push_str("            _mode: PhantomData<Mode>,\n");
        s.push_str("        }\n\n");

        s.push_str("        impl<'a, Mode> PinBuilder<'a, Mode> {\n");
        s.push_str(&indent_block(&builder_methods, 12));
        if !builder_methods.is_empty() && !builder_methods.ends_with('\n') {
            s.push('\n');
        }
        s.push_str("            #[inline(always)]\n");
        s.push_str("            pub fn build(self) -> Pin<'a, Mode> {\n");
        s.push_str(&format!(
            "                let reg = &self.port.{}[self.index as usize];\n",
            self.field_pin_cnf
        ));
        s.push_str("                reg.write(self.cnf);\n");
        s.push_str(
            "                Pin { port: self.port, index: self.index, _mode: PhantomData }\n",
        );
        s.push_str("            }\n");
        s.push_str("        }\n");

        s.push_str("    }\n");
        Ok(s)
    }
}

fn render_builder_setter(
    pin_cnf_field: &str,
    field_name: &str,
    f: &svd::Field,
    has_enum: bool,
) -> String {
    let (lsb, width) = field_lsb_width(f);
    let mask: u32 = if width >= 32 {
        u32::MAX
    } else {
        ((1u64 << width) - 1) as u32
    };
    let ty = if has_enum {
        sanitize_type_name(field_name)
    } else {
        "u32".to_string()
    };
    let arg = if has_enum { "v as u32" } else { "v" };
    let mname = sanitize_field_name(field_name);

    let mut s = String::new();

    // Special handling for DIR: provide typestate transitions into OutputMode/InputMode so that
    // set_high/set_low are only available after the required configuration.
    if field_name.eq_ignore_ascii_case("DIR") {
        let (dir_in, dir_out) = dir_input_output_values(f);

        // Keep the generic setter for backwards compatibility.
        s.push_str("            #[inline(always)]\n");
        s.push_str(&format!(
            "            pub fn {mname}(self, v: {ty}) -> Self {{\n"
        ));
        let _ = pin_cnf_field; // kept for signature compatibility; writes happen in build()
        s.push_str("                let cur = self.cnf;\n");
        s.push_str(&format!(
            "                let new = (cur & !(0x{mask:X}u32 << {lsb})) | ((({arg}) & 0x{mask:X}u32) << {lsb});\n"
        ));
        s.push_str("                PinBuilder { cnf: new, ..self }\n");
        s.push_str("            }\n\n");

        // Typestate transitions.
        s.push_str("            #[inline(always)]\n");
        s.push_str("            pub fn into_output(self) -> PinBuilder<'a, OutputMode> {\n");
        s.push_str("                let cur = self.cnf;\n");
        s.push_str(&format!(
            "                let new = (cur & !(0x{mask:X}u32 << {lsb})) | ((({dir_out}u32) & 0x{mask:X}u32) << {lsb});\n"
        ));
        s.push_str("                PinBuilder { port: self.port, index: self.index, cnf: new, _mode: PhantomData }\n");
        s.push_str("            }\n\n");

        s.push_str("            #[inline(always)]\n");
        s.push_str("            pub fn into_input(self) -> PinBuilder<'a, InputMode> {\n");
        s.push_str("                let cur = self.cnf;\n");
        s.push_str(&format!(
            "                let new = (cur & !(0x{mask:X}u32 << {lsb})) | ((({dir_in}u32) & 0x{mask:X}u32) << {lsb});\n"
        ));
        s.push_str("                PinBuilder { port: self.port, index: self.index, cnf: new, _mode: PhantomData }\n");
        s.push_str("            }\n\n");

        return s;
    }
    s.push_str("            #[inline(always)]\n");
    s.push_str(&format!(
        "            pub fn {mname}(self, v: {ty}) -> Self {{\n"
    ));
    let _ = pin_cnf_field; // kept for signature compatibility; writes happen in build()
    s.push_str("                let cur = self.cnf;\n");
    s.push_str(&format!(
        "                let new = (cur & !(0x{mask:X}u32 << {lsb})) | ((({arg}) & 0x{mask:X}u32) << {lsb});\n"
    ));
    s.push_str("                PinBuilder { cnf: new, ..self }\n");
    s.push_str("            }\n\n");
    s
}

fn dir_input_output_values(f: &svd::Field) -> (u32, u32) {
    // Try to infer from enumeratedValues; fall back to (0=input, 1=output).
    let mut input: Option<u32> = None;
    let mut output: Option<u32> = None;

    if let Some(evs) = f.enumerated_values.first() {
        for v in &evs.enumerated_value {
            let Some(val) = (match &v.spec {
                svd::EnumeratedValueSpec::Value { value } => parse_enum_u64(value),
                svd::EnumeratedValueSpec::IsDefault { .. } => None,
            }) else {
                continue;
            };
            let name = v.name.to_ascii_lowercase();
            if input.is_none() && name.contains("input") {
                input = Some(val as u32);
            }
            if output.is_none() && name.contains("output") {
                output = Some(val as u32);
            }
        }
    }

    (input.unwrap_or(0), output.unwrap_or(1))
}

fn render_field_enum(field_name: &str, f: &svd::Field) -> Option<String> {
    // Pick the first enumeratedValues block that yields at least one numeric value.
    let evs = f.enumerated_values.first()?;
    let mut vars: Vec<(String, u64)> = Vec::new();
    for v in &evs.enumerated_value {
        let Some(val) = (match &v.spec {
            svd::EnumeratedValueSpec::Value { value } => parse_enum_u64(value),
            svd::EnumeratedValueSpec::IsDefault { .. } => None,
        }) else {
            continue;
        };
        vars.push((sanitize_variant_name(&v.name), val));
    }
    if vars.is_empty() {
        return None;
    }

    let ty = sanitize_type_name(field_name);
    let mut s = String::new();
    s.push_str(&format!("        #[repr(u32)]\n"));
    s.push_str("        #[derive(Copy, Clone, Debug, PartialEq, Eq)]\n");
    s.push_str(&format!("        pub enum {ty} {{\n"));
    for (n, v) in &vars {
        s.push_str(&format!("            {n} = {v},\n"));
    }
    s.push_str("        }\n");
    Some(s)
}

fn collect_gpio_ports(device: &svd::Device) -> Vec<GpioPortInfo> {
    let mut out = Vec::new();
    for p in &device.peripherals {
        if !is_gpio_like_port(&p.name) {
            continue;
        }
        let Some(rb) = &p.registers else { continue };
        let items = rb.items.as_slice();

        let Some((pin_cnf_name, pin_cnf_reg)) = find_register(items, "PIN_CNF") else {
            continue;
        };
        let Some((outset_name, _)) = find_register(items, "OUTSET") else {
            continue;
        };
        let Some((outclr_name, _)) = find_register(items, "OUTCLR") else {
            continue;
        };

        out.push(GpioPortInfo {
            periph_name: p.name.clone(),
            periph_mod: sanitize_module_name(&p.name),
            hal_mod: sanitize_field_name(&p.name),
            field_outset: sanitize_field_name(&outset_name),
            field_outclr: sanitize_field_name(&outclr_name),
            field_pin_cnf: sanitize_field_name(&pin_cnf_name),
            pin_cnf_reg_path: pin_cnf_reg.name.clone(),
            pin_fields: pin_cnf_reg.field.clone(),
        });
    }
    out
}

fn is_gpio_like_port(name: &str) -> bool {
    // Typical Nordic: P0, P1.
    let b = name.as_bytes();
    if b.len() < 2 {
        return false;
    }
    if b[0] != b'P' && b[0] != b'p' {
        return false;
    }
    b[1..].iter().all(|c| c.is_ascii_digit())
}

fn find_register<'a>(
    items: &'a [svd::RegisterBlockItem],
    needle: &str,
) -> Option<(String, &'a svd::Register)> {
    for it in items {
        match it {
            svd::RegisterBlockItem::Register { register } => {
                if register.name.to_ascii_uppercase().contains(needle) {
                    return Some((register.name.clone(), register));
                }
            }
            svd::RegisterBlockItem::Cluster { cluster } => {
                if let Some(x) = find_register(cluster.items.as_slice(), needle) {
                    return Some(x);
                }
            }
        }
    }
    None
}

fn field_lsb_width(f: &svd::Field) -> (u32, u32) {
    match f.bit_range {
        svd::BitRange::BitRangeString { msb, lsb } => (lsb, msb.saturating_sub(lsb) + 1),
        svd::BitRange::LsbMsb { lsb, msb } => (lsb, msb.saturating_sub(lsb) + 1),
        svd::BitRange::BitOffsetWidth {
            bit_offset,
            bit_width,
        } => (bit_offset, bit_width.unwrap_or(1)),
    }
}

fn parse_enum_u64(s: &str) -> Option<u64> {
    let s = s.trim();
    let s = s.strip_prefix('+').unwrap_or(s);
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        let digits = hex.trim();
        if digits.is_empty() || digits.contains('x') || digits.contains('X') {
            return None;
        }
        u64::from_str_radix(digits, 16).ok()
    } else if let Some(bin) = s.strip_prefix("0b") {
        let digits = bin.trim();
        if digits.is_empty() || digits.contains('x') || digits.contains('X') {
            return None;
        }
        u64::from_str_radix(digits, 2).ok()
    } else if let Some(bin) = s.strip_prefix('#') {
        let digits = bin.trim();
        if digits.is_empty() || digits.contains('x') || digits.contains('X') {
            return None;
        }
        u64::from_str_radix(digits, 2).ok()
    } else if s.chars().all(|c| c.is_ascii_digit()) {
        s.parse::<u64>().ok()
    } else {
        None
    }
}

fn sanitize_file_stem(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "device".to_string()
    } else {
        out
    }
}

fn sanitize_module_name(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        let good = ch.is_ascii_alphanumeric() || ch == '_';
        let ch = if good { ch } else { '_' };
        if i == 0 && ch.is_ascii_digit() {
            out.push('_');
        }
        out.push(ch);
    }
    if out.is_empty() {
        "PERIPH".to_string()
    } else if is_rust_keyword(&out.to_ascii_lowercase()) {
        format!("{out}_")
    } else {
        out
    }
}

fn sanitize_field_name(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        let good = ch.is_ascii_alphanumeric() || ch == '_';
        let ch = if good { ch } else { '_' };
        if i == 0 && ch.is_ascii_digit() {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    if out.is_empty() {
        "_field".to_string()
    } else if is_rust_keyword(&out) {
        format!("{out}_")
    } else {
        out
    }
}

fn sanitize_type_name(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push('_');
            }
            if upper_next {
                out.push(ch.to_ascii_uppercase());
                upper_next = false;
            } else {
                out.push(ch.to_ascii_lowercase());
            }
        } else {
            upper_next = true;
        }
    }
    if out.is_empty() {
        "Type".to_string()
    } else if is_rust_keyword(&out.to_ascii_lowercase()) {
        format!("{out}_")
    } else {
        out
    }
}

fn sanitize_variant_name(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push('_');
            }
            if upper_next {
                out.push(ch.to_ascii_uppercase());
                upper_next = false;
            } else {
                out.push(ch.to_ascii_lowercase());
            }
        } else {
            upper_next = true;
        }
    }
    if out.is_empty() {
        "Value".to_string()
    } else if is_rust_keyword(&out.to_ascii_lowercase()) {
        format!("{out}_")
    } else {
        out
    }
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

fn indent_block(s: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    s.lines()
        .map(|l| {
            if l.is_empty() {
                "\n".to_string()
            } else {
                format!("{pad}{l}\n")
            }
        })
        .collect()
}
