use crate::Result;
use crate::hal::ir::*;
use crate::hal::common::*;

pub fn emit_timer_file(timers: &[TimerIr], pac_crate: &str) -> Result<String> {
    let mut s = String::new();
    s.push_str("// AUTO-GENERATED BY svdkit::hal::timer\n");
    s.push_str("#[allow(dead_code)]\n");
    s.push_str("#[allow(non_snake_case)]\n\n");
    s.push_str("use super::pac;\n\n");
    for t in timers {
        s.push_str(&emit_timer(t, pac_crate));
        s.push('\n');
    }
    Ok(s)
}

pub fn emit_timer(t: &TimerIr, _pac_crate: &str) -> String {
    let mut s = String::new();
    let timer_ty = &t.timer_type_name;
    let mod_name = &t.hal_mod;

    s.push_str(&format!("    pub mod {mod_name} {{\n"));
    s.push_str("        #[allow(dead_code)]\n");
    s.push_str("        #[allow(non_snake_case)]\n\n");
    s.push_str(&format!("        pub type {timer_ty} = crate::pac::peripherals::{}::{timer_ty};\n\n", t.periph_mod));
    s.push_str("        use core::marker::PhantomData;\n\n");
    s.push_str("        pub trait TimerModeTrait {}\n");
    s.push_str("        pub struct Unconfigured;\n");
    s.push_str("        impl TimerModeTrait for Unconfigured {}\n\n");

    s.push_str("        #[inline(always)]\n");
    s.push_str(&format!("        pub unsafe fn steal() -> &'static {timer_ty} {{\n            &*crate::pac::peripherals::{}::PTR\n        }}\n\n", t.periph_mod));
    s.push_str(&format!("        pub fn timer() -> Timer<'static, Unconfigured> {{\n            Timer {{ t: unsafe {{ &*crate::pac::peripherals::{}::PTR }}, _mode: PhantomData }}\n        }}\n\n", t.periph_mod));

    let mode_alias = sanitize_type_name("MODE");
    if t.mode_enum_is_pac {
        s.push_str(&format!("        pub use crate::pac::peripherals::{}::enums::{} as {mode_alias};\n\n", t.periph_mod, pac_mode_enum_name(t)));
    } else if let Some(ref def) = t.mode_enum_local_def {
        s.push_str(&indent_block(def, 8));
        s.push('\n');
    }
    let mode_ty = if t.mode_enum_is_pac || t.mode_enum_local_def.is_some() {
        mode_alias.clone()
    } else {
        "u32".to_string()
    };
    let mode_arg = if t.mode_enum_is_pac || t.mode_enum_local_def.is_some() { "v as u32" } else { "v" };

    let bitmode_alias = sanitize_type_name("BITMODE");
    if t.bitmode_enum_is_pac {
        s.push_str(&format!("        pub use crate::pac::peripherals::{}::enums::{} as {bitmode_alias};\n\n", t.periph_mod, pac_bitmode_enum_name(t)));
    } else if let Some(ref def) = t.bitmode_enum_local_def {
        s.push_str(&indent_block(def, 8));
        s.push('\n');
    }
    let bitmode_ty = if t.bitmode_enum_is_pac || t.bitmode_enum_local_def.is_some() {
        bitmode_alias.clone()
    } else {
        "u32".to_string()
    };
    let bitmode_arg = if t.bitmode_enum_is_pac || t.bitmode_enum_local_def.is_some() { "v as u32" } else { "v" };

    s.push_str(&format!("        pub struct Timer<'a, M: TimerModeTrait> {{\n            t: &'a {timer_ty},\n            _mode: PhantomData<M>,\n        }}\n\n"));
    s.push_str(&format!("        impl<'a> Timer<'a, Unconfigured> {{\n"));
    s.push_str("            #[inline(always)]\n");
    s.push_str("            pub fn configure(self) -> TimerConfigurator<'a> {\n");
    s.push_str("                TimerConfigurator {\n                    t: self.t,\n                    mode_val: None,\n                    bitmode_val: None,\n                    prescaler_val: None,\n                    cc_vals: [None, None, None, None, None, None],\n                    clear_on_compare_mask: None,\n                    interrupt_mask: None,\n                }\n");
    s.push_str("            }\n        }\n\n");
    s.push_str(&format!("        pub struct TimerConfigurator<'a> {{\n            t: &'a {timer_ty},\n            mode_val: Option<u32>,\n            bitmode_val: Option<u32>,\n            prescaler_val: Option<u32>,\n            cc_vals: [Option<u32>; 6],\n            clear_on_compare_mask: Option<u32>,\n            interrupt_mask: Option<u32>,\n        }}\n\n"));
    s.push_str("        impl<'a> TimerConfigurator<'a> {\n");
    s.push_str("            #[inline(always)]\n");
    s.push_str(&format!("            pub fn mode(self, v: {mode_ty}) -> Self {{\n                TimerConfigurator {{\n                    t: self.t,\n                    mode_val: Some({mode_arg}),\n                    bitmode_val: self.bitmode_val,\n                    prescaler_val: self.prescaler_val,\n                    cc_vals: self.cc_vals,\n                    clear_on_compare_mask: self.clear_on_compare_mask,\n                    interrupt_mask: self.interrupt_mask,\n                }}\n            }}\n\n"));
    s.push_str("            #[inline(always)]\n");
    s.push_str(&format!("            pub fn bitmode(self, v: {bitmode_ty}) -> Self {{\n                TimerConfigurator {{\n                    t: self.t,\n                    mode_val: self.mode_val,\n                    bitmode_val: Some({bitmode_arg}),\n                    prescaler_val: self.prescaler_val,\n                    cc_vals: self.cc_vals,\n                    clear_on_compare_mask: self.clear_on_compare_mask,\n                    interrupt_mask: self.interrupt_mask,\n                }}\n            }}\n\n"));
    s.push_str("            #[inline(always)]\n            pub fn prescaler(self, v: u32) -> Self {\n                TimerConfigurator { t: self.t, mode_val: self.mode_val, bitmode_val: self.bitmode_val, prescaler_val: Some(v), cc_vals: self.cc_vals, clear_on_compare_mask: self.clear_on_compare_mask, interrupt_mask: self.interrupt_mask }\n            }\n\n");
    s.push_str("            #[inline(always)]\n            pub fn cc(self, index: usize, v: u32) -> Self {\n                let mut vals = self.cc_vals;\n                if index < vals.len() { vals[index] = Some(v); }\n                TimerConfigurator { t: self.t, mode_val: self.mode_val, bitmode_val: self.bitmode_val, prescaler_val: self.prescaler_val, cc_vals: vals, clear_on_compare_mask: self.clear_on_compare_mask, interrupt_mask: self.interrupt_mask }\n            }\n\n");
    s.push_str("            #[inline(always)]\n            pub fn clear_on_compare(self, index: usize, enable: bool) -> Self {\n                let mut mask = self.clear_on_compare_mask.unwrap_or(0);\n                match index {\n");
    for cf in &t.shorts_fields {
        s.push_str(&format!("                {} => {{ mask = (mask & !(0x{mask_field:X}u32 << {lsb})) | ((if enable {{ 1 }} else {{ 0 }}) << {lsb}); }}\n", cf.index, mask_field = cf.mask, lsb = cf.lsb));
    }
    s.push_str("                _ => {}\n            }\n            TimerConfigurator { t: self.t, mode_val: self.mode_val, bitmode_val: self.bitmode_val, prescaler_val: self.prescaler_val, cc_vals: self.cc_vals, clear_on_compare_mask: Some(mask), interrupt_mask: self.interrupt_mask }\n        }\n\n");
    s.push_str("            #[inline(always)]\n            pub fn enable_interrupt_on_compare(self, index: usize) -> Self {\n                let mut mask = self.interrupt_mask.unwrap_or(0);\n                match index {\n");
    for cf in &t.intenset_fields {
        s.push_str(&format!("                {} => {{ mask = (mask & !(0x{mask_field:X}u32 << {lsb})) | (1u32 << {lsb}); }}\n", cf.index, mask_field = cf.mask, lsb = cf.lsb));
    }
    s.push_str("                _ => {}\n            }\n            TimerConfigurator { t: self.t, mode_val: self.mode_val, bitmode_val: self.bitmode_val, prescaler_val: self.prescaler_val, cc_vals: self.cc_vals, clear_on_compare_mask: self.clear_on_compare_mask, interrupt_mask: Some(mask) }\n        }\n\n");

    s.push_str("            #[inline(always)]\n            pub fn apply(self) -> TimerConfigured<'a> {\n");
    s.push_str(&format!("                if let Some(v) = self.bitmode_val {{\n                    let cur = self.t.{0}.read();\n                    let new = (cur & !(0x{bm:X}u32 << {bl})) | ((v & 0x{bm:X}u32) << {bl});\n                    self.t.{0}.write(new);\n                }}\n", t.field_bitmode, bm = t.bitmode_mask, bl = t.bitmode_lsb));
    s.push_str("                if let Some(v) = self.prescaler_val {\n");
    s.push_str(&format!("                    self.t.{}.write(v);\n                }}\n", t.field_prescaler));
    s.push_str("                for (i, v) in self.cc_vals.iter().enumerate() {\n");
    s.push_str(&format!("                    if i < self.t.{}.len() {{ if let Some(val) = v {{ self.t.{}[i].write(*val); }} }}\n                }}\n", t.field_cc, t.field_cc));
    s.push_str("                if let Some(v) = self.clear_on_compare_mask {\n");
    s.push_str(&format!("                    self.t.{}.write(v);\n                }}\n", t.field_shorts));
    s.push_str("                if let Some(v) = self.interrupt_mask {\n");
    s.push_str(&format!("                    self.t.{}.write(v);\n                }}\n", t.field_intenset));
    s.push_str(&format!("                if let Some(v) = self.mode_val {{\n                    let cur = self.t.{0}.read();\n                    let new = (cur & !(0x{m:X}u32 << {ml})) | ((v & 0x{m:X}u32) << {ml});\n                    self.t.{0}.write(new);\n                }}\n", t.field_mode, m = t.mode_mask, ml = t.mode_lsb));
    s.push_str("                if let Some(v) = self.mode_val {\n                    match v {\n                        0 => TimerConfigured::Timer(TimerModeTimer(self.t)),\n                        1 => TimerConfigured::Counter(TimerModCounter(self.t)),\n                        2 => TimerConfigured::LowPowerCounter(TimerModeLowPowerCounter(self.t)),\n                        _ => TimerConfigured::Timer(TimerModeTimer(self.t)),\n                    }\n                } else {\n                    TimerConfigured::Timer(TimerModeTimer(self.t))\n                }\n            }\n        }\n\n");
    s.push_str("        pub enum TimerConfigured<'a> { Timer(TimerModeTimer<'a>), Counter(TimerModCounter<'a>), LowPowerCounter(TimerModeLowPowerCounter<'a>) }\n\n");
    s.push_str(&format!("        pub struct TimerModeTimer<'a>(pub &'a {timer_ty});\n"));
    s.push_str(&format!("        pub struct TimerModCounter<'a>(pub &'a {timer_ty});\n"));
    s.push_str(&format!("        pub struct TimerModeLowPowerCounter<'a>(pub &'a {timer_ty});\n\n"));

    for mode_ty_name in &["TimerModeTimer", "TimerModCounter", "TimerModeLowPowerCounter"] {
        s.push_str(&format!("        impl<'a> {mode_ty_name}<'a> {{\n"));
        s.push_str("            #[inline(always)]\n            pub fn clear_event_compare(self, index: usize) -> Self {\n");
        s.push_str(&format!("                if index < self.0.{}.len() {{ self.0.{}[index].write(0); }}\n                self\n            }}\n\n", t.field_events_compare, t.field_events_compare));
        s.push_str("            #[inline(always)]\n            pub fn clear(self) -> Self {\n");
        s.push_str(&format!("                self.0.{}.write(1);\n                self\n            }}\n\n", t.field_tasks_clear));
        s.push_str("            #[inline(always)]\n            pub fn start(self) -> Self {\n");
        s.push_str(&format!("                self.0.{}.write(1);\n                self\n            }}\n", t.field_tasks_start));
        s.push_str("        }\n\n");
    }

    s.push_str("    }\n");
    s
}

fn pac_mode_enum_name(t: &TimerIr) -> &str {
    &t.mode_enum_name
}

fn pac_bitmode_enum_name(t: &TimerIr) -> &str {
    &t.bitmode_enum_name
}
